### ISSUE TITLE
pip installation fails on MacOS

### ISSUE THREAD

**Issue by aschenbecherwespe** [panda-official/WaveletBuffer#18]
With the following output:

```
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Collecting wavelet-buffer
  Downloading wavelet-buffer-0.1.0.tar.gz (12 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: wavelet-buffer
  Building wheel for wavelet-buffer (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/opt/python@3.9/bin/python3.9 /usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /var/folders/8g/1c8plht92j10yc_fx9904wg40000gq/T/tmp88k4e3n4
       cwd: /private/var/folders/8g/1c8plht92j10yc_fx9904wg40000gq/T/pip-install-n_xldp0_/wavelet-buffer_d66d912b984149f0b139a2f3d91a640a
  Complete output (88 lines):
  Not searching for unused variables given on the command line.
  -- The C compiler identification is AppleClang 13.0.0.13000027
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- The CXX compiler identification is AppleClang 13.0.0.13000027
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /private/var/folders/8g/1c8plht92j10yc_fx9904wg40000gq/T/pip-install-n_xldp0_/wavelet-buffer_d66d912b984149f0b139a2f3d91a640a/_cmake_test_compile/build
  -- The C compiler identification is AppleClang 13.0.0.13000027
  -- The CXX compiler identification is AppleClang 13.0.0.13000027
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  CMake Error at CMakeLists.txt:5 (add_subdirectory):
    The source directory
  
      /private/var/folders/8g/1c8plht92j10yc_fx9904wg40000gq/T/pip-install-n_xldp0_
  
    does not contain a CMakeLists.txt file.
  
  
  '/usr/local/Cellar/python@3.9/3.9.7/bin/python3.9' '-c' 'import pybind11; print(pybind11.get_cmake_dir())'
  -- Found PythonInterp: /usr/local/Cellar/python@3.9/3.9.7/bin/python3.9 (found version "3.9.7")
  -- Found PythonLibs: /usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/libpython3.9.dylib
  -- Performing Test HAS_FLTO
  -- Performing Test HAS_FLTO - Success
  -- Performing Test HAS_FLTO_THIN
  -- Performing Test HAS_FLTO_THIN - Success
  -- Found pybind11: /private/var/folders/8g/1c8plht92j10yc_fx9904wg40000gq/T/pip-build-env-8v3feplv/overlay/lib/python3.9/site-packages/pybind11/include (found version "2.9.2")
  -- Configuring incomplete, errors occurred!
  See also "/private/var/folders/8g/1c8plht92j10yc_fx9904wg40000gq/T/pip-install-n_xldp0_/wavelet-buffer_d66d912b984149f0b139a2f3d91a640a/_skbuild/macosx-12.0-x86_64-3.9/cmake-build/CMakeFiles/CMakeOutput.log".
  See also "/private/var/folders/8g/1c8plht92j10yc_fx9904wg40000gq/T/pip-install-n_xldp0_/wavelet-buffer_d66d912b984149f0b139a2f3d91a640a/_skbuild/macosx-12.0-x86_64-3.9/cmake-build/CMakeFiles/CMakeError.log".
    File "/private/var/folders/8g/1c8plht92j10yc_fx9904wg40000gq/T/pip-build-env-8v3feplv/overlay/lib/python3.9/site-packages/skbuild/setuptools_wrap.py", line 637, in setup
      env = cmkr.configure(
    File "/private/var/folders/8g/1c8plht92j10yc_fx9904wg40000gq/T/pip-build-env-8v3feplv/overlay/lib/python3.9/site-packages/skbuild/cmaker.py", line 328, in configure
      raise SKBuildError(
  
  
  --------------------------------------------------------------------------------
  -- Trying "Ninja" generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying "Ninja" generator - success
  --------------------------------------------------------------------------------
  
  Configuring Project
    Working directory:
      /private/var/folders/8g/1c8plht92j10yc_fx9904wg40000gq/T/pip-install-n_xldp0_/wavelet-buffer_d66d912b984149f0b139a2f3d91a640a/_skbuild/macosx-12.0-x86_64-3.9/cmake-build
    Command:
      cmake /private/var/folders/8g/1c8plht92j10yc_fx9904wg40000gq/T/pip-install-n_xldp0_/wavelet-buffer_d66d912b984149f0b139a2f3d91a640a -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/private/var/folders/8g/1c8plht92j10yc_fx9904wg40000gq/T/pip-install-n_xldp0_/wavelet-buffer_d66d912b984149f0b139a2f3d91a640a/_skbuild/macosx-12.0-x86_64-3.9/cmake-install/src/wavelet_buffer -DPYTHON_VERSION_STRING:STRING=3.9.7 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/private/var/folders/8g/1c8plht92j10yc_fx9904wg40000gq/T/pip-build-env-8v3feplv/overlay/lib/python3.9/site-packages/skbuild/resources/cmake -DPython3_EXECUTABLE:FILEPATH=/usr/local/Cellar/python@3.9/3.9.7/bin/python3.9 -DPython3_INCLUDE_DIR:PATH=/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -DPython3_LIBRARY:PATH=/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/libpython3.9.dylib -DPython3_NumPy_INCLUDE_DIRS:PATH=/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/numpy/core/include -DPython_EXECUTABLE:FILEPATH=/usr/local/Cellar/python@3.9/3.9.7/bin/python3.9 -DPython_INCLUDE_DIR:PATH=/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -DPython_LIBRARY:PATH=/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/libpython3.9.dylib -DPython_NumPy_INCLUDE_DIRS:PATH=/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/numpy/core/include -DPYTHON_EXECUTABLE:FILEPATH=/usr/local/Cellar/python@3.9/3.9.7/bin/python3.9 -DPYTHON_INCLUDE_DIR:PATH=/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -DPYTHON_LIBRARY:PATH=/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/libpython3.9.dylib -DPYTHON_NumPy_INCLUDE_DIRS:PATH=/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/numpy/core/include -DCMAKE_MAKE_PROGRAM:FILEPATH=/private/var/folders/8g/1c8plht92j10yc_fx9904wg40000gq/T/pip-build-env-8v3feplv/overlay/lib/python3.9/site-packages/ninja/data/bin/ninja -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=12.0 -DCMAKE_OSX_ARCHITECTURES:STRING=x86_64
  
  Traceback (most recent call last):
  
  An error occurred while configuring with CMake.
    Command:
      cmake /private/var/folders/8g/1c8plht92j10yc_fx9904wg40000gq/T/pip-install-n_xldp0_/wavelet-buffer_d66d912b984149f0b139a2f3d91a640a -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/private/var/folders/8g/1c8plht92j10yc_fx9904wg40000gq/T/pip-install-n_xldp0_/wavelet-buffer_d66d912b984149f0b139a2f3d91a640a/_skbuild/macosx-12.0-x86_64-3.9/cmake-install/src/wavelet_buffer -DPYTHON_VERSION_STRING:STRING=3.9.7 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/private/var/folders/8g/1c8plht92j10yc_fx9904wg40000gq/T/pip-build-env-8v3feplv/overlay/lib/python3.9/site-packages/skbuild/resources/cmake -DPython3_EXECUTABLE:FILEPATH=/usr/local/Cellar/python@3.9/3.9.7/bin/python3.9 -DPython3_INCLUDE_DIR:PATH=/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -DPython3_LIBRARY:PATH=/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/libpython3.9.dylib -DPython3_NumPy_INCLUDE_DIRS:PATH=/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/numpy/core/include -DPython_EXECUTABLE:FILEPATH=/usr/local/Cellar/python@3.9/3.9.7/bin/python3.9 -DPython_INCLUDE_DIR:PATH=/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -DPython_LIBRARY:PATH=/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/libpython3.9.dylib -DPython_NumPy_INCLUDE_DIRS:PATH=/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/numpy/core/include -DPYTHON_EXECUTABLE:FILEPATH=/usr/local/Cellar/python@3.9/3.9.7/bin/python3.9 -DPYTHON_INCLUDE_DIR:PATH=/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -DPYTHON_LIBRARY:PATH=/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/libpython3.9.dylib -DPYTHON_NumPy_INCLUDE_DIRS:PATH=/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/numpy/core/include -DCMAKE_MAKE_PROGRAM:FILEPATH=/private/var/folders/8g/1c8plht92j10yc_fx9904wg40000gq/T/pip-build-env-8v3feplv/overlay/lib/python3.9/site-packages/ninja/data/bin/ninja -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=12.0 -DCMAKE_OSX_ARCHITECTURES:STRING=x86_64
    Source directory:
      /private/var/folders/8g/1c8plht92j10yc_fx9904wg40000gq/T/pip-install-n_xldp0_/wavelet-buffer_d66d912b984149f0b139a2f3d91a640a
    Working directory:
      /private/var/folders/8g/1c8plht92j10yc_fx9904wg40000gq/T/pip-install-n_xldp0_/wavelet-buffer_d66d912b984149f0b139a2f3d91a640a/_skbuild/macosx-12.0-x86_64-3.9/cmake-build
  Please see CMake's output for more information.
  ----------------------------------------
  ERROR: Failed building wheel for wavelet-buffer
Failed to build wavelet-buffer
ERROR: Could not build wheels for wavelet-buffer which use PEP 517 and cannot be installed directly
WARNING: You are using pip version 21.2.4; however, version 22.1.2 is available.
You should consider upgrading via the '/usr/local/opt/python@3.9/bin/python3.9 -m pip install --upgrade pip' command.
```

**Comment by aschenbecherwespe** [comment]
Trying to build the latest version directly from git:

```
% pip3 install git+https://github.com/panda-official/WaveletBuffer.git#subdirectory=python


DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Collecting git+https://github.com/panda-official/WaveletBuffer.git#subdirectory=python
  Cloning https://github.com/panda-official/WaveletBuffer.git to /private/var/folders/8g/1c8plht92j10yc_fx9904wg40000gq/T/pip-req-build-56ikaru3
  Running command git clone -q https://github.com/panda-official/WaveletBuffer.git /private/var/folders/8g/1c8plht92j10yc_fx9904wg40000gq/T/pip-req-build-56ikaru3
  Resolved https://github.com/panda-official/WaveletBuffer.git to commit 1d810fbb502c0d22ca8b6b6ab496f4db87bb4bf0
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: wavelet-buffer
  Building wheel for wavelet-buffer (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/opt/python@3.9/bin/python3.9 /usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /var/folders/8g/1c8plht92j10yc_fx9904wg40000gq/T/tmpu_qvqy_v
       cwd: /private/var/folders/8g/1c8plht92j10yc_fx9904wg40000gq/T/pip-req-build-56ikaru3/python
  Complete output (105 lines):
  Not searching for unused variables given on the command line.
  -- The C compiler identification is AppleClang 13.0.0.13000027
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- The CXX compiler identification is AppleClang 13.0.0.13000027
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /private/var/folders/8g/1c8plht92j10yc_fx9904wg40000gq/T/pip-req-build-56ikaru3/python/_cmake_test_compile/build
  -- The C compiler identification is AppleClang 13.0.0.13000027
  -- The CXX compiler identification is AppleClang 13.0.0.13000027
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Downloading conan.cmake from https://github.com/conan-io/cmake-conan
  -- Conan: checking conan executable
  -- Conan: Found program /private/var/folders/8g/1c8plht92j10yc_fx9904wg40000gq/T/pip-build-env-le3ybnin/overlay/bin/conan
  -- Conan: Version found Conan version 1.41.0
  -- Conan executing: /private/var/folders/8g/1c8plht92j10yc_fx9904wg40000gq/T/pip-build-env-le3ybnin/overlay/bin/conan install . --remote conancenter --build missing --settings build_type=Release --settings compiler=apple-clang --settings compiler.version=13.0 --settings compiler.libcxx=libc++
  Configuration:
  [settings]
  arch=x86_64
  arch_build=x86_64
  build_type=Release
  compiler=apple-clang
  compiler.libcxx=libc++
  compiler.version=13.0
  os=Macos
  os_build=Macos
  [options]
  [build_requires]
  [env]
  
  openblas/0.3.20: Retrieving from server 'conancenter'
  openblas/0.3.20: Trying with 'conancenter'...
  Downloading conanmanifest.txt
  Downloading conanfile.py
  Downloading conan_export.tgz
  openblas/0.3.20: Downloaded recipe revision 0
  ERROR: openblas/0.3.20: Cannot load recipe.
  Error loading conanfile at '/Users/moyne/.conan/data/openblas/0.3.20/_/_/export/conanfile.py': Current Conan version (1.41.0) does not satisfy the defined one (>=1.43.0).
  CMake Error at _skbuild/macosx-12.0-x86_64-3.9/cmake-build/conan.cmake:651 (message):
    Conan install failed='1'
  Call Stack (most recent call first):
    /private/var/folders/8g/1c8plht92j10yc_fx9904wg40000gq/T/pip-req-build-56ikaru3/CMakeLists.txt:36 (conan_cmake_install)
  
  
  -- Configuring incomplete, errors occurred!
  See also "/private/var/folders/8g/1c8plht92j10yc_fx9904wg40000gq/T/pip-req-build-56ikaru3/python/_skbuild/macosx-12.0-x86_64-3.9/cmake-build/CMakeFiles/CMakeOutput.log".
  See also "/private/var/folders/8g/1c8plht92j10yc_fx9904wg40000gq/T/pip-req-build-56ikaru3/python/_skbuild/macosx-12.0-x86_64-3.9/cmake-build/CMakeFiles/CMakeError.log".
    File "/private/var/folders/8g/1c8plht92j10yc_fx9904wg40000gq/T/pip-build-env-le3ybnin/overlay/lib/python3.9/site-packages/skbuild/setuptools_wrap.py", line 637, in setup
      env = cmkr.configure(
    File "/private/var/folders/8g/1c8plht92j10yc_fx9904wg40000gq/T/pip-build-env-le3ybnin/overlay/lib/python3.9/site-packages/skbuild/cmaker.py", line 328, in configure
      raise SKBuildError(
  
  
  --------------------------------------------------------------------------------
  -- Trying "Ninja" generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying "Ninja" generator - success
  --------------------------------------------------------------------------------
  
  Configuring Project
    Working directory:
      /private/var/folders/8g/1c8plht92j10yc_fx9904wg40000gq/T/pip-req-build-56ikaru3/python/_skbuild/macosx-12.0-x86_64-3.9/cmake-build
    Command:
      cmake /private/var/folders/8g/1c8plht92j10yc_fx9904wg40000gq/T/pip-req-build-56ikaru3/python -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/private/var/folders/8g/1c8plht92j10yc_fx9904wg40000gq/T/pip-req-build-56ikaru3/python/_skbuild/macosx-12.0-x86_64-3.9/cmake-install/src/wavelet_buffer -DPYTHON_VERSION_STRING:STRING=3.9.7 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/private/var/folders/8g/1c8plht92j10yc_fx9904wg40000gq/T/pip-build-env-le3ybnin/overlay/lib/python3.9/site-packages/skbuild/resources/cmake -DPython3_EXECUTABLE:FILEPATH=/usr/local/Cellar/python@3.9/3.9.7/bin/python3.9 -DPython3_INCLUDE_DIR:PATH=/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -DPython3_LIBRARY:PATH=/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/libpython3.9.dylib -DPython3_NumPy_INCLUDE_DIRS:PATH=/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/numpy/core/include -DPython_EXECUTABLE:FILEPATH=/usr/local/Cellar/python@3.9/3.9.7/bin/python3.9 -DPython_INCLUDE_DIR:PATH=/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -DPython_LIBRARY:PATH=/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/libpython3.9.dylib -DPython_NumPy_INCLUDE_DIRS:PATH=/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/numpy/core/include -DPYTHON_EXECUTABLE:FILEPATH=/usr/local/Cellar/python@3.9/3.9.7/bin/python3.9 -DPYTHON_INCLUDE_DIR:PATH=/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -DPYTHON_LIBRARY:PATH=/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/libpython3.9.dylib -DPYTHON_NumPy_INCLUDE_DIRS:PATH=/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/numpy/core/include -DCMAKE_MAKE_PROGRAM:FILEPATH=/private/var/folders/8g/1c8plht92j10yc_fx9904wg40000gq/T/pip-build-env-le3ybnin/overlay/lib/python3.9/site-packages/ninja/data/bin/ninja -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=12.0 -DCMAKE_OSX_ARCHITECTURES:STRING=x86_64
  
  Traceback (most recent call last):
  
  An error occurred while configuring with CMake.
    Command:
      cmake /private/var/folders/8g/1c8plht92j10yc_fx9904wg40000gq/T/pip-req-build-56ikaru3/python -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/private/var/folders/8g/1c8plht92j10yc_fx9904wg40000gq/T/pip-req-build-56ikaru3/python/_skbuild/macosx-12.0-x86_64-3.9/cmake-install/src/wavelet_buffer -DPYTHON_VERSION_STRING:STRING=3.9.7 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/private/var/folders/8g/1c8plht92j10yc_fx9904wg40000gq/T/pip-build-env-le3ybnin/overlay/lib/python3.9/site-packages/skbuild/resources/cmake -DPython3_EXECUTABLE:FILEPATH=/usr/local/Cellar/python@3.9/3.9.7/bin/python3.9 -DPython3_INCLUDE_DIR:PATH=/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -DPython3_LIBRARY:PATH=/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/libpython3.9.dylib -DPython3_NumPy_INCLUDE_DIRS:PATH=/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/numpy/core/include -DPython_EXECUTABLE:FILEPATH=/usr/local/Cellar/python@3.9/3.9.7/bin/python3.9 -DPython_INCLUDE_DIR:PATH=/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -DPython_LIBRARY:PATH=/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/libpython3.9.dylib -DPython_NumPy_INCLUDE_DIRS:PATH=/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/numpy/core/include -DPYTHON_EXECUTABLE:FILEPATH=/usr/local/Cellar/python@3.9/3.9.7/bin/python3.9 -DPYTHON_INCLUDE_DIR:PATH=/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -DPYTHON_LIBRARY:PATH=/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/libpython3.9.dylib -DPYTHON_NumPy_INCLUDE_DIRS:PATH=/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/numpy/core/include -DCMAKE_MAKE_PROGRAM:FILEPATH=/private/var/folders/8g/1c8plht92j10yc_fx9904wg40000gq/T/pip-build-env-le3ybnin/overlay/lib/python3.9/site-packages/ninja/data/bin/ninja -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=12.0 -DCMAKE_OSX_ARCHITECTURES:STRING=x86_64
    Source directory:
      /private/var/folders/8g/1c8plht92j10yc_fx9904wg40000gq/T/pip-req-build-56ikaru3/python
    Working directory:
      /private/var/folders/8g/1c8plht92j10yc_fx9904wg40000gq/T/pip-req-build-56ikaru3/python/_skbuild/macosx-12.0-x86_64-3.9/cmake-build
  Please see CMake's output for more information.
  ----------------------------------------
  ERROR: Failed building wheel for wavelet-buffer
Failed to build wavelet-buffer
ERROR: Could not build wheels for wavelet-buffer which use PEP 517 and cannot be installed directly
```

**Comment by aschenbecherwespe** [comment]
I uninstalled an existsing `conan=1.41.0` version, and tried again, and was able to successfully install directly from the directory in the repo. Installing from PyPI still doesn't work.

**Comment by atimin** [comment]
Looks like the pip package is broken. I have the same behavior on Linux.

**Comment by victor1234** [comment]
@flipback Should I add macos to `cibuildwheels` ?

**Comment by atimin** [comment]
> @flipback Should I add macos to `cibuildwheels` ?

It is not related to OS. The source package is broken and don't have all the C++ sources.

**Comment by victor1234** [comment]
> > @flipback Should I add macos to `cibuildwheels` ?
> 
> It is not related to OS. The source package is broken and don't have all the C++ sources.

Of course but if we build macos package, no need to build it from source if yser side. We shoud do both for my opinion

**Comment by aschenbecherwespe** [comment]
Seems to be fixed! Thanks!
