### ISSUE TITLE
Bug: pip install git+https://github.com/panda-official/WaveletBuffer.git crashes on Ubuntu 20.04

### ISSUE THREAD

**Issue by atimin** [panda-official/WaveletBuffer#26]
### What happened?

I can't install WaveletBuffer from git:

```
pip install git+https://github.com/panda-official/WaveletBuffer.git 
```

### Version

develop (8ee1b5714e5ff859d85d1af4607c707dbedc3f1b)

### OS

Linux

### Programming Language

Python, C++

### Logs

```Shell
pip install git+https://github.com/panda-official/WaveletBuffer.git
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/panda-official/WaveletBuffer.git
  Cloning https://github.com/panda-official/WaveletBuffer.git to /tmp/pip-req-build-4gw0xrbe
  Running command git clone --filter=blob:none --quiet https://github.com/panda-official/WaveletBuffer.git /tmp/pip-req-build-4gw0xrbe
  Resolved https://github.com/panda-official/WaveletBuffer.git to commit 8ee1b5714e5ff859d85d1af4607c707dbedc3f1b
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: wavelet-buffer
  Building wheel for wavelet-buffer (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for wavelet-buffer (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [126 lines of output]
      Not searching for unused variables given on the command line.
      -- The C compiler identification is GNU 9.4.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is GNU 9.4.0
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done
      -- Generating done
      -- Build files have been written to: /tmp/pip-req-build-4gw0xrbe/_cmake_test_compile/build
      -- The C compiler identification is GNU 9.4.0
      -- The CXX compiler identification is GNU 9.4.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Downloading conan.cmake from https://github.com/conan-io/cmake-conan
      -- Conan: checking conan executable
      -- Conan: Found program /tmp/pip-build-env-wq7b4e5g/overlay/bin/conan
      -- Conan: Version found Conan version 1.43.0
      -- Conan executing: /tmp/pip-build-env-wq7b4e5g/overlay/bin/conan install . --remote conancenter --build missing --settings build_type=Release --settings compiler=gcc --settings compiler.version=9 --settings compiler.libcxx=libstdc++11
      Configuration:
      [settings]
      arch=x86_64
      arch_build=x86_64
      build_type=Release
      compiler=gcc
      compiler.libcxx=libstdc++11
      compiler.version=9
      os=Linux
      os_build=Linux
      [options]
      [build_requires]
      [env]
      
      openblas/0.3.20: Retrieving from server 'conancenter'
      openblas/0.3.20: Trying with 'conancenter'...
      Downloading conanmanifest.txt
      Downloading conanfile.py
      Downloading conan_export.tgz
      openblas/0.3.20: Downloaded recipe revision 0
      blaze/3.8: Retrieving from server 'conancenter'
      blaze/3.8: Trying with 'conancenter'...
      Downloading conanmanifest.txt
      Downloading conanfile.py
      Downloading conan_export.tgz
      blaze/3.8: Downloaded recipe revision 0
      libjpeg-turbo/2.1.2: Retrieving from server 'conancenter'
      libjpeg-turbo/2.1.2: Trying with 'conancenter'...
      Downloading conanmanifest.txt
      Downloading conanfile.py
      Downloading conan_export.tgz
      libjpeg-turbo/2.1.2: Downloaded recipe revision 0
      ERROR: libjpeg-turbo/2.1.2: Cannot load recipe.
      Error loading conanfile at '/home/atimin/.conan/data/libjpeg-turbo/2.1.2/_/_/export/conanfile.py': Unable to load conanfile in /home/atimin/.conan/data/libjpeg-turbo/2.1.2/_/_/export/conanfile.py
        File "/usr/lib/python3.8/imp.py", line 171, in load_source
          module = _load(spec)
        File "<frozen importlib._bootstrap>", line 702, in _load
        File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 848, in exec_module
        File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
        File "/home/atimin/.conan/data/libjpeg-turbo/2.1.2/_/_/export/conanfile.py", line 3, in <module>
          from conan.tools.microsoft import is_msvc
      ImportError: cannot import name 'is_msvc' from 'conan.tools.microsoft' (/usr/local/lib/python3.8/dist-packages/conan/tools/microsoft/__init__.py)
      
      CMake Error at /tmp/pip-req-build-4gw0xrbe/_skbuild/linux-x86_64-3.8/cmake-build/conan.cmake:651 (message):
        Conan install failed='1'
      Call Stack (most recent call first):
        /tmp/pip-req-build-4gw0xrbe/CMakeLists.txt:36 (conan_cmake_install)
      
      
      -- Configuring incomplete, errors occurred!
      See also "/tmp/pip-req-build-4gw0xrbe/_skbuild/linux-x86_64-3.8/cmake-build/CMakeFiles/CMakeOutput.log".
        File "/tmp/pip-build-env-wq7b4e5g/overlay/lib/python3.8/site-packages/skbuild/setuptools_wrap.py", line 637, in setup
          env = cmkr.configure(
        File "/tmp/pip-build-env-wq7b4e5g/overlay/lib/python3.8/site-packages/skbuild/cmaker.py", line 328, in configure
          raise SKBuildError(
      
      
      --------------------------------------------------------------------------------
      -- Trying "Ninja" generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying "Ninja" generator - success
      --------------------------------------------------------------------------------
      
      Configuring Project
        Working directory:
          /tmp/pip-req-build-4gw0xrbe/_skbuild/linux-x86_64-3.8/cmake-build
        Command:
          cmake /tmp/pip-req-build-4gw0xrbe/python -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-req-build-4gw0xrbe/_skbuild/linux-x86_64-3.8/cmake-install/python/src/wavelet_buffer -DPYTHON_VERSION_STRING:STRING=3.8.10 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-wq7b4e5g/overlay/lib/python3.8/site-packages/skbuild/resources/cmake -DPython3_EXECUTABLE:FILEPATH=/usr/bin/python3 -DPython3_INCLUDE_DIR:PATH=/usr/include/python3.8 -DPython3_LIBRARY:PATH=/usr/lib/x86_64-linux-gnu/libpython3.8.so -DPython3_NumPy_INCLUDE_DIRS:PATH=/usr/local/lib/python3.8/dist-packages/numpy/core/include -DPython_EXECUTABLE:FILEPATH=/usr/bin/python3 -DPython_INCLUDE_DIR:PATH=/usr/include/python3.8 -DPython_LIBRARY:PATH=/usr/lib/x86_64-linux-gnu/libpython3.8.so -DPython_NumPy_INCLUDE_DIRS:PATH=/usr/local/lib/python3.8/dist-packages/numpy/core/include -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.8 -DPYTHON_LIBRARY:PATH=/usr/lib/x86_64-linux-gnu/libpython3.8.so -DPYTHON_NumPy_INCLUDE_DIRS:PATH=/usr/local/lib/python3.8/dist-packages/numpy/core/include -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-wq7b4e5g/overlay/lib/python3.8/site-packages/ninja/data/bin/ninja -DCMAKE_BUILD_TYPE:STRING=Release
      
      Traceback (most recent call last):
      
      An error occurred while configuring with CMake.
        Command:
          cmake /tmp/pip-req-build-4gw0xrbe/python -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-req-build-4gw0xrbe/_skbuild/linux-x86_64-3.8/cmake-install/python/src/wavelet_buffer -DPYTHON_VERSION_STRING:STRING=3.8.10 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-wq7b4e5g/overlay/lib/python3.8/site-packages/skbuild/resources/cmake -DPython3_EXECUTABLE:FILEPATH=/usr/bin/python3 -DPython3_INCLUDE_DIR:PATH=/usr/include/python3.8 -DPython3_LIBRARY:PATH=/usr/lib/x86_64-linux-gnu/libpython3.8.so -DPython3_NumPy_INCLUDE_DIRS:PATH=/usr/local/lib/python3.8/dist-packages/numpy/core/include -DPython_EXECUTABLE:FILEPATH=/usr/bin/python3 -DPython_INCLUDE_DIR:PATH=/usr/include/python3.8 -DPython_LIBRARY:PATH=/usr/lib/x86_64-linux-gnu/libpython3.8.so -DPython_NumPy_INCLUDE_DIRS:PATH=/usr/local/lib/python3.8/dist-packages/numpy/core/include -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.8 -DPYTHON_LIBRARY:PATH=/usr/lib/x86_64-linux-gnu/libpython3.8.so -DPYTHON_NumPy_INCLUDE_DIRS:PATH=/usr/local/lib/python3.8/dist-packages/numpy/core/include -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-wq7b4e5g/overlay/lib/python3.8/site-packages/ninja/data/bin/ninja -DCMAKE_BUILD_TYPE:STRING=Release
        Source directory:
          /tmp/pip-req-build-4gw0xrbe/python
        Working directory:
          /tmp/pip-req-build-4gw0xrbe/_skbuild/linux-x86_64-3.8/cmake-build
      Please see CMake's output for more information.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for wavelet-buffer
Failed to build wavelet-buffer
ERROR: Could not build wheels for wavelet-buffer, which is required to install pyproject.toml-based projects
```
```


### Attachments

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atimin** [comment]
I think the most important part:
```
 File "/home/atimin/.conan/data/libjpeg-turbo/2.1.2/_/_/export/conanfile.py", line 3, in <module>
          from conan.tools.microsoft import is_msvc
      ImportError: cannot import name 'is_msvc' from 'conan.tools.microsoft' (/usr/local/lib/python3.8/dist-packages/conan/tools/microsoft/__init__.py)
      
      CMake Error at /tmp/pip-req-build-4gw0xrbe/_skbuild/linux-x86_64-3.8/cmake-build/conan.cmake:651 (message):
        Conan install failed='1'
      Call Stack (most recent call first):
        /tmp/pip-req-build-4gw0xrbe/CMakeLists.txt:36 (conan_cmake_install)
```
@victor1234 maybe we have to update conan in `pyproject.tom;`?

**Comment by atimin** [comment]
Required version of conan is >= 1.50. Unfortunately, if a user has a system conan of older version, this version is used, and it can break the build. They should update their system conan manually.
